config/routes.rb
Rails.application.routes.draw do
  root 'projects#home'

  devise_for :users

  get '/users/:id', to: 'users#show', as: :user_profile

  resources :projects
  get 'explore' => 'projects#index'
  post '/projects/:id/fundings', to: 'projects#create_funding', as: :project_funding

end

app/models/funding.rb
class Funding < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates :amount,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than: 0,
              less_than: 100_000
            }
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, foreign_key: :owner_id, class_name: :User
  has_many :fundings, class_name: :Funding
  has_many :funders, class_name: :User, through: :fundings, source: :user
  validates :name, presence: true, length: { maximum: 30 }
  validates :target_amount,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than: 0,
              less_than: 1_000_000
            }
  validates :deadline, presence: true
  validates_date :deadline,
                 after: -> { Date.today },
                 after_message: 'must be after today'

  scope :order_by_date, (lambda do
    order('created_at desc')
  end)

  def uniq_funders
    funders.uniq
  end

  def current_amount
    fundings.sum(:amount)
  end

  def open?
    Time.new < deadline
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, foreign_key: :owner_id
  has_many :fundings
  validates :name, presence: true, length: { maximum: 30 },
                   uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  def total_funding
    fundings.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper Datetime

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:home, :index, :show]

  def home
    render layout: false
  end

  def index
    @projects = Project.order_by_date
  end

  def new
    @project = Project.new
  end

  def create
    Project.transaction do
      @project = Project.new(filter_params)
      @project.owner_id = current_user.id
      @project.save!
    end
    redirect_to project_path(@project.id)
  rescue ActiveRecord::ActiveRecordError
    respond_to do |format|
      format.html { render 'new' }
    end
  end

  def show
    @project = Project.find(params[:id])
    @funding = Funding.new
  end

  def edit
    @project = Project.find(params[:id])
    only_allow_owner
  end

  def update
    @project = Project.find(params[:id])
    only_allow_owner
    Project.transaction do
      @project.update_attributes(filter_params)
      @project.save!
    end
    redirect_to project_path(@project.id)
  rescue ActiveRecord::ActiveRecordError
    respond_to do |format|
      format.html { render 'edit' }
    end
  end

  def destroy
    @project = Project.find(params[:id])
    only_allow_owner
    Project.transaction do
      @project.destroy!
    end
    redirect_to projects_path
  rescue ActiveRecord::ActiveRecordError
    respond_to do |format|
      format.html { render 'show' }
    end
  end

  def create_funding
    Funding.transaction do
      @project = Project.find(params[:id])
      @funding = Funding.new(filter_funding_params)
      @funding.user = current_user
      @funding.project = @project
      @funding.save!
    end
    redirect_to project_path(@project)
  rescue ActiveRecord::ActiveRecordError
    respond_to do |format|
      format.html { render 'show' }
    end
  end

  private

  def filter_params
    return nil unless params[:project]
    params
      .require(:project)
      .permit([:name, :description, :deadline, :target_amount])
  end

  def filter_funding_params
    return nil unless params[:funding]
    params.require(:funding).permit([:amount])
  end

  def only_allow_owner
    return if @project && @project.owner_id == current_user.id
    render template: 'shared/forbidden'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetime.rb
module Datetime
  def display_time(datetime)
    datetime.to_time.strftime('%d %B, %Y')
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdFunding</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= google_webfonts_init({
    google: ['Roboto Slab', 'Roboto']
  }) %>
</head>

<body>

<%= render 'shared/navbar' %>
<%= render 'shared/header' %>

<div class='container'>
  <%= yield %>
</div>

<%= render 'shared/footer' %>

</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project, 
    defaults: { required: false },
    html: { class: "project-form" } do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger">
      Please view the errors below:
    </div>
  <% end %>

  <%= f.input :name, autofocus: true %>
  <%= f.input :deadline,
  						label: 'Close Date',
              as: :date %>
  <%= f.input :target_amount, as: :string %>
  <%= f.input :description, as: :text %>

  <%= f.button :submit, class: 'btn btn-warning' %>
<% end %>

app/views/projects/edit.html.erb
<div class="create">
  <div class="container">
    <div class="create-page">
      <div class="create-info">
        <h3><%= @project.name %></h3>
      </div>
      <div class="update-form">
        <%= render partial: 'form', locals: { project: @project } %>
      </div>
    </div>
  </div>
</div>

app/views/projects/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdFunding</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body style="background-image: url(<%= image_path('cover')%>) ">

<div id="cover">
  <div id="title">
    <h1>CROWD FUNDING</h1>
  </div>
  <div id="cover-explore-btn" class="row">
    <%= button_to "Explore", 
        explore_path, 
        method: :get,
        class: "btn btn-warning btn-lg" %>
  </div>
</div>

</body>
</html>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>All Projects</h1>
</div>

<% @projects.each do |project| %>
  <% current_amount = project.current_amount %>
  <% target_amount = project.target_amount %>
  <% progress = (current_amount > target_amount ? 100 : current_amount.to_f / target_amount * 100).round(0) %>
  <a href=<%= project_path(project) %>>
  <div class="project-item-wrapper col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <div class="thumbnail project-item" data-link=<%= project_path(project) %>>
      <div class="caption">
        <div class="project-list-title">
          <%= project.name %>
        </div>

        <div class="inline">
          <% if project.open? %>
            <span class="label label-success">
              <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>
              OPEN
            </span>
          <% else %>
            <span class="label label-danger">
              <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
              CLOSED
            </span>
          <% end %>
        </div>

        <div class="inline">
          <span class="label label-warning">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <%= project.owner.name %>
          </span>
        </div>

        <div class="progress">
          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="<%= progress %>" aria-valuemin="0" aria-valuemax="100" style="<%= "width: #{progress}%" %>">
            <%= progress %>%
          </div>
        </div>

        <div>
          <div>
            <span class="important">$<%= current_amount %></span> PLEDGED OF <span class="important">$<%= target_amount %></span> GOAL
          </div>

          <div>
            <span class="important"><%= project.uniq_funders.length %></span> PLEDGER<%= 'S' if project.uniq_funders.length > 1 %> 
          </div>

          <div>
            <% if project.open? %>
              <% days_remaining = ((project.deadline - Time.zone.now).to_f / 1.day).ceil %>
              <span class="important"><%= days_remaining %></span> DAY<%= 'S' if days_remaining > 1 %> LEFT
            <% else %>
              CLOSED ON <span class="important"><%= display_time(project.deadline) %></span>
            <% end %>
          </div>
        </div>

        <div class="project-item-date">
          <div>
            Created at <%= display_time(project.created_at) %>. 
          </div>
          <div>
            Lastest updated at <%= display_time(project.updated_at) %>.
          </div>
        </div>
      </div>
    </div>
  </div>
  </a>
<% end %>

app/views/projects/new.html.erb
<div class="create">
  <div class="container">
    <div class="page-header">
      <h1>Create a Project</h1>
    </div>
    <%= render partial: 'form', locals: { project: @project } %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="page-header">
  <h1><%= @project.name %></h1>
  <% if @project.owner == current_user %>
    <div class="operation-groups row">
      <%= link_to edit_project_path(@project.id), class: "btn btn-warning" do %>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        EDIT
      <% end %>

      <% if @project.fundings.empty? %>
        <%= link_to project_path(@project.id), 
            method: :delete, 
            data: {confirm: "Are you sure to delete this project?"},
            class: "btn btn-danger" do %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          DELETE
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<% current_amount = @project.current_amount %>
<% target_amount = @project.target_amount %>
<% progress = (current_amount > target_amount ? 100 : current_amount.to_f / target_amount * 100).round(0) %>

<div class="sidebar col-lg-4 col-md-4 col-sm-4 col-xs-12">
  <div class="thumbnail">
    <div class="caption">
      <div class="progress">
        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="<%= progress %>" aria-valuemin="0" aria-valuemax="100" style="<%= "width: #{progress}%" %>">
          <%= progress %>%
        </div>
      </div>

      <div class="well well-sm">
        <div>
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          By <%= link_to @project.owner.name, user_profile_path(@project.owner) %>
        </div>

        <div>
          <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
          Created at <%= display_time(@project.created_at) %>
        </div>

        <div>
          <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
          Updated at <%= display_time(@project.updated_at) %>
        </div>
      </div>

      <div class="well well-sm">
        <div>
          <span class="important">$<%= current_amount %></span> pledged of <span class="important">$<%= target_amount %></span> goal
        </div>

        <div>
          <span class="important"><%= @project.uniq_funders.length %></span>  pledgers
        </div>

        <% if @project.open? %>
          <div>
            <% days_remaining = (@project.deadline - Time.zone.now).to_i / 1.day %>
            <span class="important"><%= days_remaining %></span> days to go
          </div>
        <% else %>
          Closed on <span class="important"><%= display_time(@project.deadline) %></span>
        <% end %>
      </div>

      <div class="well well-sm">
        <div class="important">Description:</div>
        <% if @project.description.present? %>
          <%= @project.description %>
        <% else %>
          This project has no description.
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="list-group col-lg-8 col-md-8 col-sm-8 col-xs-12">
  <% if @project.fundings.any? %>
    <div class="list-group-item list-group-item-warning">
      Total <span class="important">$<%= current_amount %></span> pledged
    </div>
    <% @project.fundings.each do |funding| %>
      <div class="list-group-item indented">
        <%= link_to funding.user.name, user_profile_path(funding.user) %> pledged <span class="important">$<%= funding.amount %></span> at <%= display_time(funding.created_at) %>
      </div>
    <% end %>
  <% else %>
    <div class="list-group-item disabled">No funding now</div>
  <% end %>

  <% if @project.open? %>
    <%= simple_form_for @funding, 
        url: project_funding_path, 
        defaults: {required: false} do |f| %>

      <% if @funding.errors.any? %>
        <ul class="alert alert-danger funding-errors">
          <% @funding.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>

      <%= f.input :amount, label: false, as: :string, wrapper_html: { class: 'input-group' } %>

      <%= f.button :submit, 'Contribute', class: 'btn btn-warning', id: 'funding-submit' %>
    <% end %>
  <% else %>
    <h2>This project has been closed.</h2>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<!-- footer -->
<div class="footer">
	<div class="container">
		<p class="text-muted">Copyright &copy; 2015 CS2102 Group42</p>
	</div>
</div>
<!-- footer -->

app/views/shared/_header.html.erb
<!-- header -->
<div class="header">
</div>
<!-- //header -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse" style="margin:0">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'Home', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse" >
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'New Project', new_project_path %></li>
        <li><%= link_to 'Explore', explore_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Hello, #{current_user.name}",  user_profile_path(current_user) %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete%></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/forbidden.html.erb
<h1>You don't have this permission!</h1>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User Profile</h1>
  <h4> <%= @user.name %> &lt;<%= @user.email%>&gt;</h4>
</div>

<div class="list-group">
  <div class="list-group-item list-group-item-warning">
    Own Projects
  </div>
  <% if @user.projects.any? %>
    <% @user.projects.each do |project| %>
      <a href=<%= project_path(project) %> class="list-group-item indented">
        <%= project.name %>
      </a>
    <% end %>
  <% else %>
    <div class="list-group-item indented">No project now</div>
  <% end %>

  <div class="list-group-item list-group-item-warning">
    Funding History - <span class="important">$<%= @user.total_funding %></span> in total
  </div>
  <% if @user.fundings.any? %>
    <% @user.fundings.each do |funding| %>
      <a href=<%= project_path(funding.project) %> class="list-group-item indented">
        Funded <span class="important project-name"><%= funding.project.name %></span> for $<%= funding.amount %> at <%= display_time(funding.created_at)%> s
      </a>
    <% end %>
  <% else %>
    <div class="list-group-item indented">No fundings now</div>
  <% end %>
</div>